# Generated by Django 3.0.7 on 2023-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
    ]
