# Generated by Django 3.0.7 on 2023-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0002_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARC_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc_number', models.CharField(max_length=200)),
            ],
        ),
    ]
