# Generated by Django 3.0.7 on 2023-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0004_item_number_sac_number_service_description_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=200)),
            ],
        ),
    ]
